name: Promote Dev to Main

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  promote:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create PR from dev to main
        run: |
          gh pr create \
            --base main \
            --head dev \
            --title "Promote dev to main" \
            --body "Automated promotion PR from dev to main."
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}


