name: Promote Dev to Main

on:
  workflow_dispatch:

jobs:
  promote:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Check if PR already exists
        id: check_pr
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          head: dev
          search: true

      - name: Create PR if not exists
        if: steps.check_pr.outputs.pull-request-number == ''
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: 'Promote changes from dev to main'
          body: 'This PR promotes the latest changes from dev into the main branch.'
          base: main
          head: dev
